# Generated by Django 2.1.2 on 2018-10-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lhuser',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='lhuser',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='lhuser',
            name='second_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='second name'),
        ),
    ]
